const CACHORROS = [
  {
    nome: "Afonso",
    foto: "Imagens/Afonso.png",
    emoji: "🐶",
    idade: "5 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Resgatado em uma construção em Mauá junto com a Pilar. Corriam risco de cair no fosso do elevador pois ficavam em um andar mais elevado",
    tags: ["Dócil", "Brincalhão", "Tranquilo"]
  },

    {
    nome: "João",
    foto: "Imagens/joao.jpeg",
    emoji: "🐶",
    idade: "6 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: " tinha um dono, mas o mesmo faleceu e foi jogado na rua junto com sua amiga Maria, que já foi adotada",
    tags: ["Dócil", "Brincalhão", "Tranquilo"]
  },

    {
    nome: "Bono",
    foto: "Imagens/bono.jpeg",
    emoji: "🐶",
    idade: "11 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Não",
    afinidade_gatos: "Não",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Não",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Sim",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: " uma protetora o achou ao fazer um asseio pelo parque. O Bono havia sido abandonado há uma semana amarrado a uma árvore e já tinha um ferimento no pescoço por causa da corda",
    tags: ["Dócil", "Idoso", "Tranquilo"]
  },

    {
    nome: "Mercedes",
    foto: "Imagens/mercedes.jpeg",
    emoji: "🐶",
    idade: "4 anos",
    porte: "Médio",
    sexo: "Fêmea",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Sim",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: " resgatada em parelheiros. Tutor a mantinha amarrada",
    tags: ["Dócil", "Brincalhão", "Agitada"]
  },

];