const CACHORROS = [
  {
    nome: "Afonso",
    foto: "Imagens/Afonso.png",
    emoji: "🐶",
    idade: "5 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Resgatado em uma construção em Mauá junto com a Pilar. Corriam risco de cair no fosso do elevador pois ficavam em um andar mais elevado",
    tags: ["Dócil", "Brincalhão", "Tranquilo"]
  },

    {
    nome: "João",
    foto: "Imagens/joao.jpeg",
    emoji: "🐶",
    idade: "6 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Tinha um dono, mas o mesmo faleceu e foi jogado na rua junto com sua amiga Maria, que já foi adotada",
    tags: ["Dócil", "Brincalhão", "Tranquilo"]
  },

    {
    nome: "Bono",
    foto: "Imagens/bono.jpeg",
    emoji: "🐶",
    idade: "11 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Não",
    afinidade_gatos: "Não",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Não",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Sim",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Uma protetora o achou ao fazer um asseio pelo parque. O Bono havia sido abandonado há uma semana amarrado a uma árvore e já tinha um ferimento no pescoço por causa da corda",
    tags: ["Dócil", "Idoso", "Tranquilo"]
  },

    {
    nome: "Mercedes",
    foto: "Imagens/mercedes.jpeg",
    emoji: "🐶",
    idade: "4 anos",
    porte: "Médio",
    sexo: "Fêmea",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Sim",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: " resgatada em parelheiros. Tutor a mantinha amarrada",
    tags: ["Dócil", "Brincalhão", "Agitada"]
  },

    {
    nome: "Antônia",
    foto: "Imagens/antonia.jpeg",
    emoji: "🐶",
    idade: "7 anos",
    porte: "Médio",
    sexo: "Fêmea",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Sim",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Resgatada para castração e não conseguimos devolvê-la para o local onde vivia pois era um posto de gasolina onde ela não tinha a atenção e cuidado que merecia.",
    tags: ["Dócil", "Brincalhão", "Agitada"]
  },

    {
    nome: "Caetano",
    foto: "Imagens/caetano.jpeg",
    emoji: "🐶",
    idade: "12 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Não",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Sim, Gabapentina",
    comorbidades: "Dores articulares, faz acumputura",
    descricao: "Tinha uma tutora que recebia ajuda de uma protetora. Porém, essa tutora teve um AVC e seus filhos colocaram os cães na rua. Por conta disso, a protetora pediu ajuda para o resgate.",
    tags: ["Dócil", "Tranquilo", "Idoso"]
  },

    {
    nome: "Leila",
    foto: "Imagens/leila.jpeg",
    emoji: "🐶",
    idade: "9 anos",
    porte: "Médio",
    sexo: "Fêmea",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não Testado",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "resgatada das enchentes do Rio Grande do Sul em maio de 2024 do Abrigo Pata molhada",
    tags: ["Dócil", "Tranquila", "Idosa"]
  },

    {
    nome: "Malu",
    foto: "Imagens/malu.jpeg",
    emoji: "🐶",
    idade: "5 anos",
    porte: "Médio",
    sexo: "Fêmea",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Sim",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Assumida de outra protetora que não tinha mais condições de cuidar.",
    tags: ["Dócil", "Tranquila", "Brincalhona"]
  },

    {
    nome: "Mate",
    foto: "Imagens/mate.jpeg",
    emoji: "🐶",
    idade: "8 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Não",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não Testado",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Resgatado em maio de 2024 decorrente das enchentes do Rio Grande do Sul.",
    tags: ["Dócil", "Tranquilo", "Brincalhão"]
  },

    {
    nome: "Pistache",
    foto: "Imagens/pistache.jpeg",
    emoji: "🐶",
    idade: "6 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Não",
    late_muito: "Não",
    possessivo: "Não Testado",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Os donos conseguiram um pitbull filhote e o colocaram para fora de casa. Resgatamos ele da mesma região que um outro aumigo e que ele já foi adotado.",
    tags: ["Dócil", "Agitado", "Brincalhão"]
  },

    {
    nome: "Timão",
    foto: "Imagens/timao.jpeg",
    emoji: "🐶",
    idade: "5 anos",
    porte: "Médio",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Sim",
    late_muito: "Não",
    possessivo: "Não Testado",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "Resgatado em parelheiros junto com o Pumba. Já estava na lista de resgate há um tempo.Adoção conjunta com Pumba",
    tags: ["Dócil", "Agitado", "Brincalhão"]
  },

    {
    nome: "Zion",
    foto: "Imagens/zion.jpeg",
    emoji: "🐶",
    idade: "6 anos",
    porte: "Grande",
    sexo: "Macho",
    castrado: "Sim",
    vacinado: "Sim, V10 e Raiva",
    afinidade_caes: "Sim",
    afinidade_gatos: "Não Testado",
    gosta_de_carinho: "Sim",
    gosta_de_brincar: "Sim",
    gosta_de_passear: "Sim",
    agitado: "Sim",
    pula_muito: "Sim",
    late_muito: "Não",
    possessivo: "Não Testado",
    medicacao_continua: "Não",
    comorbidades: "Não",
    descricao: "É da mesma família do Gael e Dante. Vivia preso em um lugar minúsculo e depois a família o soltou na rua.",
    tags: ["Dócil", "Agitado", "Brincalhão"]
  },

];